#!/usr/bin/env bash
# Sum a specific column from whitespace-separated input
# Usage: sum_col <col_num> [file]
if [ $# -eq 0 ] || [ $# -gt 2 ]; then
  echo "Usage: sum_col <col_num> [file]" >&2
  exit 1
fi
col="$1"; shift
if [ $# -eq 1 ]; then
  cat "$1"
else
  cat
fi | tr '\t' ' ' | tr -s ' ' | awk "{ print \$$col }" | jq -nR '[inputs | select(length>0) | tonumber] | add'
